# Generated by Django 4.2.6 on 2023-12-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capitalid', models.IntegerField(primary_key=True, serialize=False)),
                ('capitalname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.IntegerField(primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
            ],
        ),
    ]
