# Generated by Django 4.2.6 on 2023-12-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_accessrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
    ]
